# {#projectName} Technical Documentation

This README was automatically generated by PHPProjectInitializer.
If this paragraph is still present it probably means nobody's
bothered to write any project-specific documentation, yet.

## Folder structure

- ```composer.json``` - PHP package and dependency information, used by Composer.
- ```init-*.php``` - Scripts to initialize global state in PHP.
- ```lib/``` - PHP libraries defined by this project.
- ```vendor/``` - External PHP libraries, managed by Composer.
- ```config/``` - Deployment configuration;
  generally deployment-specific config files should not be checked in, here.
- ```www/``` - Serves as the 'document root' for your project.
  Contains files to be served directly and a ```.htaccess``` and ```bootstrap.php```
  to handle paths that don't correspond to existing files.
